DROP TABLE IF EXISTS `S_MQ_SYNLOG`;
CREATE TABLE `S_MQ_SYNLOG` (
  `LOG_ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `LOG_STATUS` INT(11) NOT NULL COMMENT '状态   1：成功 0：失败',
  `LOG_DATE` DATE NOT NULL COMMENT '时间',
  `VOUCHER` VARCHAR(2000) COMMENT 'VOUCHERJSON对象',
  `TERMINALRECORD` VARCHAR(2000) COMMENT 'TERMINALRECORDJSON对象',
  `MESSAGE` VARCHAR(2000) COMMENT '信息',
  PRIMARY KEY (`LOG_ID`)
) ENGINE=INNODB AUTO_INCREMENT=155 DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COMMENT='MQ同步日志表';

DROP TABLE IF EXISTS `S_MQ_CACHELOG`;
CREATE TABLE `S_MQ_CACHELOG` (
  `MQ_TASK_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `VOURCHER_NO` bigint(19) DEFAULT NULL COMMENT '凭证号',
  `TERMINAL_RECORD_ID` int(11) not null COMMENT '出票记录编号',
  `QUERY_TABLE` varchar(200) DEFAULT NULL COMMENT '要查询的对应表名',
  `DEL_FLAG` int COMMENT '删除标记：0:已删除 1：新增',
  `DATATIME` timestamp COMMENT '记录时间',
  `MESSAGE` varchar(2000) COMMENT '信息',
  PRIMARY KEY (`MQ_TASK_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=155 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='MQ缓存日志表';

DROP TABLE IF EXISTS `S_FTP_LOG_DATA`;
CREATE TABLE `S_FTP_LOG_DATA` (
  `ID` 						int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `CSV_DATA` 				varchar(4000) NOT NULL COMMENT 'csv文件的行的内容',
  `CSV_ROW` 				int(11) DEFAULT NULL COMMENT 'CSV文件的行数',
  `FTP_FILE_PATH`	 		varchar(128) DEFAULT NULL COMMENT 'FTP的文件全路径',
  `LOCAL_FILE_PATH` 		varchar(128) DEFAULT NULL COMMENT '本地下载FTP的文件全路径',
  `OPERATE_TIME` 			timestamp COMMENT '操作时间',
  UNIQUE KEY `IDX_S_FTP_LOG_DATA` (`ID`) USING HASH
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='本地服务FTP同步的日志';



DROP TABLE IF EXISTS `S_EQUIPMENT`;
CREATE TABLE `S_EQUIPMENT` (
  `EQUIPMENT_ID` 				varchar(32) NOT NULL COMMENT '设备ID',
  `EQUIPMENT_NUMBER` 			varchar(32) NOT NULL COMMENT '设备编号',
  `EQUIPMENT_TYPE` 				varchar(32) DEFAULT NULL COMMENT '设备类型(1有线，2无线)',
  `CARRIEROPERATOR`	 			varchar(32) DEFAULT NULL COMMENT '运营商',
  `EQUIPMENT_REMARKS` 			varchar(2000) DEFAULT NULL COMMENT '设备备注',
  `EQUIPMENT_STATUS` 			char(1) DEFAULT NULL COMMENT '设备状态：0已启用，1未启用',
  `EQUIPMENT_SCNIZATION_STATUS` char(1) DEFAULT '1' COMMENT '设备同步状态：0已同步，1未同步',
  `MERCHANT_ID` 				varchar(32) DEFAULT NULL COMMENT '商户ID',
  `MERCHANT_NAME` 				varchar(32) DEFAULT NULL COMMENT '商户名称',
  `IS_REGISTER` 				char(255) DEFAULT NULL COMMENT '设备签到状态：0已签到，1未签到',
  `CONECT_TYPE` 				char(2) DEFAULT NULL COMMENT '连接类型：1 GPS   2 CDMA  3有线',
  `EQUIPMENT_MODEL` 			char(2) DEFAULT NULL COMMENT '设备型号：1 MT900 2 MT1200 ',
  `SCENIC_SPOT_ID` 				VARCHAR(32) NOT NULL COMMENT '景区ID',
  UNIQUE KEY `idx_equipment_number` (`EQUIPMENT_NUMBER`) USING HASH
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='设备表';

DROP TABLE IF EXISTS `S_TERMINAL_RECORD`;
CREATE TABLE `S_TERMINAL_RECORD` (
  `TERMINAL_RECORD_ID` 			int(11) NOT NULL AUTO_INCREMENT COMMENT '终端出票序号',
  `RECORD_CHANNEL` 				varchar(16) DEFAULT NULL COMMENT '出票的渠道',
  `VOUCHER_VALUE`			 	varchar(32) DEFAULT NULL COMMENT '凭证编号(值)',
  `TRADE_NUM` 					varchar(32) DEFAULT NULL COMMENT '交易流水号',
  `TOTAL_PRICE` 				decimal(12,2) DEFAULT '0.00' COMMENT '销售总价',
  `PRINT_TIMES` 				int(4) DEFAULT '0' COMMENT '出票数量',
  `ALL_SETTLEMENT_PRICE` 		decimal(12,2) DEFAULT '0.00' COMMENT '结算总价',
  `TERMINAL_NUM` 				varchar(32) DEFAULT NULL COMMENT '终端编号',
  `ORDER_NUM` 					varchar(32) DEFAULT NULL COMMENT '订单号',
  `GOODS_ID` 					varchar(32) NOT NULL COMMENT '商品ID',
  `GOODS_NAME`					varchar(200) DEFAULT NULL COMMENT '商品名称',
  `MERCHANT_ID` 				varchar(16) DEFAULT NULL COMMENT '商户ID',
  `MERCHANT_NAME` 				varchar(32) DEFAULT NULL COMMENT '商户名称',
  `SCENIC_SPOT_ID` 				varchar(16) NOT NULL DEFAULT '0' COMMENT '景区ID',
  `SCENIC_SPOT_NAME` 			varchar(50) DEFAULT NULL COMMENT '景区名称',
  `USE_TIME` 					timestamp NULL DEFAULT NULL COMMENT '验证时间',
  `CHECKING_TYPE` 				tinyint(3) DEFAULT NULL COMMENT '验证方式。1凭证，2身份证',
  `BATCH_NO` 					varchar(16) DEFAULT NULL COMMENT '批次号',
  `NEED_SEND_VERIFY_MSG` 		tinyint(3) DEFAULT '1' COMMENT '需要发送验证信息(0否1要)',
  `CREATE_TIME` 				timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '出票时间',
  PRIMARY KEY (`TERMINAL_RECORD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='终端出票记录表';


DROP TABLE IF EXISTS `S_VOUCHER_MERCHANT`;
CREATE TABLE `S_VOUCHER_MERCHANT` (
  `VOUCHER_MERCHANT_ID` 		int(11) NOT NULL AUTO_INCREMENT COMMENT '凭证商品表ID',
  `VOUCHER_ID` 					varchar(32) NOT NULL COMMENT '凭证序号',
  `MERCHANT_ID` 				varchar(16) NOT NULL DEFAULT '0' COMMENT '商家ID',
  `MERCHANT_NAME` 				varchar(64) NOT NULL COMMENT '商家名称',
  `CAN_USE_TIMES` 				int(2) DEFAULT NULL COMMENT '在该商户里最大使用的次数',
  `USE_TIMES` 					int(2) DEFAULT NULL COMMENT '在该商户里已经使用的次数',
  `SCENIC_SPOT_ID` 				varchar(16) DEFAULT NULL COMMENT '景区ID',
  `SCENIC_SPOT_NAME` 			varchar(32) DEFAULT NULL COMMENT '景区名称',
  PRIMARY KEY (`VOUCHER_MERCHANT_ID`),
  KEY `VOUCHER_ID` (`VOUCHER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=237 DEFAULT CHARSET=utf8 COMMENT='凭证对应商户表';


drop table if exists S_LOCAL_VOUCHER;

create table S_VOUCHER
(
   `VOURCHER_NO` 		bigint(19) NOT NULL,
   `VOUCHER_ID` 		varchar(32) NOT NULL COMMENT '凭证序号',
   `ORDER_ID` 			varchar(32) NOT NULL COMMENT '订单业务ID',
   `VOUCHER_VALUE` 		varchar(32) DEFAULT NULL COMMENT '凭证值（接口产生）',
   `CERTIFICATE_NUM` 	varchar(32) DEFAULT NULL COMMENT '证件号',
   `GOODS_ID` 			varchar(32) NOT NULL COMMENT '商品ID',
   `GOODS_NAME` 		varchar(24) DEFAULT NULL COMMENT '商品名称',
   `SCENIC_SPOT_ID` 	varchar(16) DEFAULT NULL COMMENT '景区ID',
   `SCENIC_SPOT_NAME` 	varchar(32) DEFAULT NULL COMMENT '景区名称',
   `IS_PACKAGE` 		tinyint(3) DEFAULT NULL COMMENT '是否套票，0否1是2子商品',
   `PACKAGE_ID` 		varchar(32) DEFAULT NULL COMMENT '套票ID',
    `PRICE` decimal(10,2) DEFAULT '0.00' COMMENT '真实售价',
   `SUPPLIER_SETTLEMENT_PRICE` decimal(10,2) DEFAULT '0.00' COMMENT '供应商结算价',
   `VALIDATE_TIMES` int(6) DEFAULT '0' COMMENT '已验证次数',
   `MAX_USE_TIMES` int(6) DEFAULT '0' COMMENT '凭证最大使用次数',
   `CANCEL_NUM` int(6) DEFAULT '0' COMMENT '作废的数量',
   `FREEZE_NUM` int(6) DEFAULT '0' COMMENT '冻结数量，冻结数量为0表示未冻结',
   `STATUS` tinyint(3) DEFAULT '0' COMMENT '凭证状态  0:未生效 1.未使用  2.已使用  ,3:已作废 4：过期可退 5:过期退款 ,6:改期 7.部分使用',
   `IS_TICKET` tinyint(3) DEFAULT NULL COMMENT '是否打印入园凭票.1.已出 2.未出',
   `USE_TIME` timestamp NULL DEFAULT NULL COMMENT '凭证使用时间',
   `START_DATE` date DEFAULT NULL COMMENT '凭证有效期开始时间',
   `END_DATE` date DEFAULT NULL COMMENT '凭证有效期结束时间',
   `START_EXP_ALLOW_TIME` varchar(24) DEFAULT '0' COMMENT '开始时间 存的是时间的分钟数 允许门票在一天哪个时间段消费,0表示0点0分',
   `END_EXP_ALLOW_TIME` varchar(24) DEFAULT '0' COMMENT '结束时间 存的是时间的分钟数 允许门票在一天哪个时间段消费 1440表示24:00分',
   `IS_SECOND_VALID` tinyint(3) DEFAULT '0' COMMENT '是否二次验证 0:否 1:是',
   `EXP_DAY_OF_WEEK` varchar(24) DEFAULT '0' COMMENT '指定门票星期几有效，0全部，（1,2,5）表示周1周2周5',
   `EXP_EXCEPTION_DATE` varchar(240) DEFAULT '0' COMMENT '指定在门票有效期内不能使用的时间',
   `VOUCHER_IMAGE_URL` varchar(240) DEFAULT NULL COMMENT '凭证图片地址',
   `REPRINT_TIMES` INT(3) DEFAULT 0 COMMENT '重打印次数',
   `OUT_CODE` VARCHAR(64) DEFAULT NULL COMMENT '外部代码',
   `UPDATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '更新时间',
  PRIMARY KEY (`VOURCHER_NO`),
  KEY `ORDER_ID` (`ORDER_ID`),
  KEY `VOUCHER_ID` (`VOUCHER_ID`),
  KEY `VOUCHER_VALUE` (`VOUCHER_VALUE`)
) ENGINE=InnoDB AUTO_INCREMENT=22223 DEFAULT CHARSET=utf8 COMMENT='凭证表';


DROP TABLE IF EXISTS `S_SEQ`;
CREATE TABLE `S_SEQ` (
  `NAME` varchar(30) NOT NULL,
  `VAL` bigint(32) unsigned NOT NULL,
  PRIMARY KEY (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

